#!/bin/sh
###############################################################################
# 50-bcmfix-script - This script corrects Broadcom WIFI MAC address
# Written By: croniccorey (cronmod.dev@gmail.com)
# Date Written: 2014/09/19
###############################################################################

MAC=$(cat /sys/class/net/wlan0/address)
BAD_MAC=00:90:4c:11:22:33

if [ $MAC == $BAD_MAC ]; then
    nmcli nm wifi off
    nmcli nm wifi on
fi
